### ISSUE TITLE
big fan :) i might have an idea or two

### ISSUE THREAD

**Issue by Swoop376** [romen-h/ONI-Mods#1]
Hi ! the piped deodorizer is very nice !! as the germicides lamps, im a big fan i wanted to talk to you about a few mods ideas i have 

i would like to know if it were possible to have a steady feeding solution for a pacu farm 
maybe something like a plant we put in the tank and give off algae or some seed or making the pacus eat the actual plant, or a pellet that could come from a machine or from a process  maybe while harvesting or composting . these are just ideas, but theres not really longterm solution to feed a large pacu farm beside starving them. maybe even  algae growers, in real life they cultivate algae in some glass tubes who looks alot like your gemicide lamps.

Also the plug slug could need a power outlet increase and a change of diet to make them useful in a ranch  these is alot of option for modding them their diet maybe refined metals as it come from volcanoes that way....or hanging plants...maybe even eating ice 

The diseases system could use a bit of change like you could litteraly let the germ overlay go wild and almost dont notice. that would be awesome to have to usee those uvc's lamps 

finally 2 building we do have in the game already but are not used to their full potential ....1 the cryo chamber would be cool to put some dupes on  pause sometimes and the teleporter/receiver that could be use to travel from a side of the map to the other maybe ?

Of course these are juste wrote there to help you find some nice idea for more mods to com if you have the time ;) im learning C# at the moment i might even be able to mod something this year hehe

Have a nice one and keep up the good work

**Comment by romen-h** [comment]
Hi,

Thanks for the suggestions!

I think a mod that produces algae (or slime) would be something I could look at for an upcoming mod.
I think the conveyor chutes are already sort of like automatic fish feeders so I'd like to leave it up to the player's imagination on how to deliver the algae to the pacu pool :)
