### ISSUE TITLE
Thermoelectric Coolers: TEC Tile no longer appears in build menu

### ISSUE THREAD

**Issue by Senacharim** [romen-h/ONI-Mods#14]
## Steps To Reproduce
Select "Utilities" in Oxygen Not Included in an ongoing game in which the TEC Tile is already researched and which has the latest patch/update.

## REQUIRED: Logs & Screenshots
Screenshot attached.

## Other Mods
![Screenshot from 2022-02-27 14-19-59](https://user-images.githubusercontent.com/9025459/155900384-4cf82cbe-e6e4-457d-b3ae-7b05c3e3860c.png)

List the other mods you are using so I can see whether the problem is due to a conflict with any of them:
Butcher & Fishing Stations
Subscribed on Feb 19 @ 5:16pm
Last Updated Feb 26 @ 1:56am
 
Refuel Turned-Off Generators
Subscribed on Feb 6 @ 3:54pm
Last Updated Nov 15, 2021 @ 5:13am
 
Geyser Calculated Average Output Tooltip
Subscribed on Feb 6 @ 3:50pm
Last Updated Jul 2, 2021 @ 9:27am
 
Settings Change Tool
Subscribed on Feb 6 @ 3:49pm
Last Updated Feb 21 @ 1:18am

Choose Neural Vacillator
Subscribed on Feb 6 @ 3:48pm
Last Updated Jul 27, 2021 @ 6:55pm

Piped Super Computer (Advanced Research Station -- Water input Continued)
Subscribed on Feb 6 @ 10:27am
Last Updated Nov 9, 2021 @ 8:23pm

DGSM - Duplicants Generation Settings Manager // by @Ony 👾
Subscribed on Feb 5 @ 10:07pm
Last Updated Nov 29, 2021 @ 2:40am

Priority Zero
Subscribed on Jan 30 @ 12:56am
Last Updated Nov 22, 2021 @ 3:33pm

Pip Plant Overlay
Subscribed on Jan 28 @ 10:46pm
Last Updated Feb 21 @ 1:15am

Buildable Dirt Tile
Subscribed on Jan 28 @ 10:46pm
Last Updated Jun 27, 2021 @ 6:06pm

Mod Updater
Subscribed on Jan 28 @ 7:08pm
Last Updated Feb 21 @ 12:57am
 
Thermoelectric Coolers
Subscribed on Jan 28 @ 7:07pm
Last Updated Sep 16, 2021 @ 5:46pm
 
Pliers 2021
Subscribed on Jan 28 @ 7:06pm
Last Updated Jan 30 @ 1:42pm
 
Material Colored Tiles and more
Subscribed on Jan 28 @ 7:06pm
Last Updated Feb 26 @ 11:41am
 
Drywall Hides Pipes
Subscribed on Jan 28 @ 7:04pm
Last Updated Jul 24, 2021 @ 10:13am
 
Block Decor Effects Behind Walls
Subscribed on Jan 28 @ 7:04pm
Last Updated Dec 25, 2021 @ 10:41am
 
Suppress Notifications
Subscribed on Jan 28 @ 7:01pm
Last Updated Jun 27, 2021 @ 7:40pm
 
Show Industrial Machinery Tag
Subscribed on Jan 28 @ 7:00pm
Last Updated Jul 4, 2021 @ 6:31am
 
Refined Metals Usable As Raw Metals
Subscribed on Jan 28 @ 7:00pm
Last Updated Sep 16, 2021 @ 6:41pm
 
Wounded Go To Med Bed
Subscribed on Jan 28 @ 7:00pm
Last Updated Jul 2, 2021 @ 9:24am

[Vanilla + DLC] Deconstructable POI Props
Subscribed on Jan 28 @ 6:59pm
Last Updated Jul 27, 2021 @ 8:08am

Useful Tags Lite
Subscribed on Jan 28 @ 6:49pm
Last Updated Aug 24, 2021 @ 6:17am

Passive Gas Vent Input
Subscribed on Jan 28 @ 6:48pm
Last Updated Feb 6 @ 8:59am

**Comment by Senacharim** [comment]
Game update 496912

**Comment by romen-h** [comment]
Thanks, I am working on fixing all of my mods due to the new game version.
Uploading a fix in moments from now.

**Comment by Senacharim** [comment]
Thank you!

--
Thinker Code Monkey (Über cool!)
http://www.cafepress.com/thinkercodemonk.416274193
