### ISSUE TITLE
Plastic door: No longer can be built due to upstream changes

### ISSUE THREAD

**Issue by yusiangpotato** [romen-h/ONI-Mods#15]
## REQUIRED: Describe the bug
Upstream ONI broke a giant pile of mods. Many buildings cannot be built due to this change.

[https://forums.kleientertainment.com/klei-bug-tracker/oni/missing-mod-build-items-in-menu-r34127/](https://steamcommunity.com/linkfilter/?url=https://forums.kleientertainment.com/klei-bug-tracker/oni/missing-mod-build-items-in-menu-r34127/)

"Mods using our supported ModUtil.AddBuildingToPlanScreen to add buildings are unaffected. This mod is not using that method and needs to be updated by the author. "

## Steps To Reproduce
Try to build plastic door. Or to "repeat build" existing plastic door.

## REQUIRED: Logs & Screenshots
No bug or crash.
It just isn't in the build menu any longer.
![image](https://user-images.githubusercontent.com/9015310/156204017-7c4e62b2-d7d6-4603-936c-c80b30c78b4d.png)

## Other Mods
Many other mods. Some also have the same issue.

**Comment by yusiangpotato** [comment]
Game update 497575 reverted the build menu change, placing all custom buildings at the bottom of the relevant build category now.

**Comment by romen-h** [comment]
This issue is already fixed. It seems like you were using an outdated version of the mod.
Can you tell me the version number from mod_info.yaml?

**Comment by yusiangpotato** [comment]
That is odd.
In game mod manager says 3.0.1.0, but 
Documents\Klei\OxygenNotIncluded\mods\Steam\2556517152\modinfo.yaml is 3.0.0.0.

Date modified is 28/2/2022 3:25pm (GMT+8)

I suppose the point is moot now given that Klei reverted their changes, so I will close the issue. Thank you for the mods!

https://www.reddit.com/r/Oxygennotincluded/comments/t5d0y5/game_update_497575_fixed_mods/
> We also made some modding changes to better support adding buildings to the game. This may restore functionality to some mods which were adding buildings in an unorthodox way. Lastly we have an announcement to make regarding mod support, see our post here.
