### ISSUE TITLE
[Dumping Sign] Increase "Amount" of Storage

### ISSUE THREAD

**Issue by zGedson** [romen-h/ONI-Mods#18]
In the current way, the storage is set to 1000kg at a time, which creates a huge queue when the duplicates are carrying only one type of item. Maybe the increase to 10000kg is enough to stop this problem

**Comment by romen-h** [comment]
Thanks, I didn't know about this issue.

Will be fixed in the update that will also fix the missing anim crashes.

**Comment by zGedson** [comment]
Alright, managed to solve the problem for the moment. I created several signs signaling the same material, it has helped so far.
