### ISSUE TITLE
Piped Deodorizer

### ISSUE THREAD

**Issue by SCIENTIST2004** [romen-h/ONI-Mods#2]
The building is a little bit buggy it starts working then immediately stops

**Comment by romen-h** [comment]
I think you are seeing the same issue others have mentioned in the steam comments.

Does it just stop taking more polluted oxygen? Can you post a screenshot showing the storage values and maybe the mass in the pipe at the input?

**Comment by ProgFrock** [comment]
Hi Romen!  It just stops taking the polluted oxygen in - it just sits there in the pipes.  I was keeping an eye on it yesterday to see if it stopped when a certain level of polluted dirt built up, but it seems to be pretty random.  If you deconstruct and rebuild then it'll work again for a time then stop.

**Comment by unselchr** [comment]
Has there been any progress on this subject? It still seems to be an issue. I am running the base game without dlc or any mods that change how gasses move through pipes. There is the high gas pressure in the input pipes, no gas in my output pipes, and there are random amounts of polluted dirt in several non-working deodorizers that I have.

**Comment by romen-h** [comment]
I have a fix but I have not been keeping up with the state of ONI mod development.
I plan to release the fix in the near future when Klei will require almost all mods to be updated anyway.

**Comment by romen-h** [comment]
This should be fixed in the latest build.
