### ISSUE TITLE
[Plastic Door] Crash when a dupe walks through the door

### ISSUE THREAD

**Issue by Maelztrom** [romen-h/ONI-Mods#20]
Any time, even on a fresh asteroid, a dupe walks through a plastic door, the game crashes.

MissingFieldException: Field 'PathFinder/Path/Node.transitionId' not found.

Curtain.Flutterable.UpdateMovement (Pickupable dupe) (at <9dddfae13306405cb310afa802ec0c70>:0)
Curtain.Flutterable.OnPickupablesChanged (System.Object obj) (at <9dddfae13306405cb310afa802ec0c70>:0)
ScenePartitioner.RunEntries (System.Collections.Generic.List`1[T] gathered_entries, System.Object event_data) (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)
ScenePartitioner.TriggerEvent (System.Int32 x, System.Int32 y, System.Int32 width, System.Int32 height, ScenePartitionerLayer layer, System.Object event_data) (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)
GameScenePartitioner.TriggerEvent (System.Int32 x, System.Int32 y, System.Int32 width, System.Int32 height, ScenePartitionerLayer layer, System.Object event_data) (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)
GameScenePartitioner.TriggerEvent (System.Int32 cell, ScenePartitionerLayer layer, System.Object event_data) (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)
Pickupable.NotifyChanged (System.Int32 new_cell) (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)
Pickupable.OnCellChange () (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)
CellChangeMonitor.RenderEveryTick () (at <3366109ff608488f8317d0b43357f1ba>:0)
Game.Update () (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)

Build: U42-509629-S

I'm making a list of my other mods

**Comment by Maelztrom** [comment]
[Player.log](https://github.com/romen-h/ONI-Mods/files/8837052/Player.log)

**Comment by romen-h** [comment]
I uploaded version 3.0.2 of the mod to the workshop.
Please confirm if that fixed the crash for you.
