### ISSUE TITLE
Crash when "Clothing" filter is selected

### ISSUE THREAD

**Issue by AznBlusuazn** [romen-h/ONI-Mods#23]
When using the "Dumping Sign" mod, if the Clothing filter is selected and there is Clothing item on available to be swept into the Dumping Sign, my game crashes.

Steps:
-  have a clothing item (snazzy suit, atmo suit, etc.) available for a dupe to sweep
-  place dumping sign
-  select filter for "clothing" items
-  game crashes

I have confirmed this with a sandbox game as well with ONLY this mod running.  Thanks.

**Comment by romen-h** [comment]
You need to share a crash log, I have no idea what the issue is

Also I'm pretty sure that I fixed this so please use Mod Updater to be sure you are not telling me about a bug in an old version of the mod.

**Comment by AznBlusuazn** [comment]
Hello.  So I'm used the v1.0.1 version of the mod...  Strangely, now it's not happening.  I will continue on.  If it happens again, I will grab the player.log.  Sorry about the inconvenience.  Thanks for your attention.
