### ISSUE TITLE
[Stirling Engine] DTU/W doesn't show up under GUI Config

### ISSUE THREAD

**Issue by Fatmice** [romen-h/ONI-Mods#28]
## REQUIRED: Describe the bug
DTU/W is configurable within config.json but not shown under GUI Config.  This was previously visible in 3.0.1.0 (ie before the fixes for #25 ).  Not a big deal, but thought I should mention it.

## Steps To Reproduce
Play on ONI 514967

## REQUIRED: Logs & Screenshots
![Screenshot from 2022-10-10 19-24-45](https://user-images.githubusercontent.com/8956281/194972119-0187a0ea-2545-4a38-9d08-ba557f467eea.png)
![Screenshot from 2022-10-10 19-31-49](https://user-images.githubusercontent.com/8956281/194972284-b97aae89-14de-4a46-8643-e15fb4665866.png)

**Comment by romen-h** [comment]
3.0.1 is the version I released that fixes issue #25 and I just released that this week.

Your screenshots show the setting missing in 3.0.0, which is an old version. The version that was available before the update this week.

If you're playing on "previous_update" branch (514967) then you are correctly loading the 3.0.0 version of the mod which never had that setting all along.

If you're playing on the current branch (525812) then it should load 3.0.1 and the setting has become available in that version.

**Comment by Fatmice** [comment]
> If you're playing on "previous_update" branch (514967) then you are correctly loading the 3.0.0 version of the mod which never had that setting in the UI. Even older versions hid the setting too.
 
That is not true. That's the reason why I showed the sha256sum. I still retain the copy of the 3.0.0 dll before #25 fixes.  The DTU/W config is there in the GUI.

But it doesn't really matter. Here's the backup before your update on Update: Oct 7 @ 9:58am

Rename to .dll
![StirlingEngine.png](https://user-images.githubusercontent.com/8956281/195250382-4f1175b0-9ff5-422d-bbb4-fa1d575c0af9.png)

**Comment by romen-h** [comment]
I just noticed I released two different 3.0.1 versions.
But what I said about DTU/W not showing up in the UI still stands true. The version I released on Oct 7 is the first version ever to show it in the UI. The "old" 3.0.1 did not show it in the UI either. I checked the git history and dates and I'm sure about that.

For some reason I didn't have a backup of the original 3.0.1 so my build system copied 3.0.0 to the previous_update folder. I simultaneously forgot to bump the version to 3.0.2.

Also I cannot accept a DLL uploaded by someone for security reasons. Especially because the DLL is going to be distributed on the workshop. I do not have a way to recover the old 3.0.1 build unfortunately, how did you get a copy of it?

**Comment by Fatmice** [comment]
Ah, you don't have to accept anything.  I think you miss-understand me.  The dll that I uploaded was yours on the steam workshop. If you still had the old one, you could verify that it's unmodified and in no way was tampered with.  There is a way to still download previous versions of the workshop item, but only if you know their GID.  As for how I got a copy of it, I make backups of all mods that I use in case major bugs are introduced when they update or steam simply remove them for whatever reason.

As for the DTU/W config, feel free to scan the dll for malicious content.  Indeed, feel free to do sha256sum on the one I uploaded to convince yourself it's the same one that I showed in the 42-072022-FastFriends-514967 backup folder.  Further, if you feel comfortable, you ought to replace the "archived_version" dll with that one to see that what I said about the DTU/W config being visible in the GUI is true, i.e. I didn't lie or make stuff up =).  But it's entirely pointless and moot and my main point was to raise it to you for awareness.  I didn't expect anything to be done about it =).  Lastly, no, I didn't asked or expected for you to upload that dll to rectify anything on steam worksthop for the archived version.
