### ISSUE TITLE
[Germicidal UV Lamps] Game crash when the lamp is activated

### ISSUE THREAD

**Issue by Stecat94** [romen-h/ONI-Mods#36]
## REQUIRED: Describe the bug
Game crash when the lamp is activated (either when plugged in if already enabled, or if you disable first, then crash on enable.) Happens to both lamps. I tested 3 times.

## Steps To Reproduce
Just build and plug-in lamp.

## REQUIRED: Logs & Screenshots
MissingMethodException: bool Grid.TestLineOfSight(int,int,int,int,System.Func`2<int, bool>,bool)

RomenH.GermicideLamp.GermicideLamp.UpdateCell (System.Single dt, System.Int32 x, System.Int32 y, System.Collections.Generic.HashSet`1[T] buildingsAlreadySeen) (at <597f3d3d76c94012aee35849ab20d17a>:0)
RomenH.GermicideLamp.GermicideLamp.Sim200ms (System.Single dt) (at <597f3d3d76c94012aee35849ab20d17a>:0)
SimAndRenderScheduler+Sim200msUpdater.Update (ISim200ms updater, System.Single dt) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <0f4b778ef79c497e89f6ee18303840cf>:0)
Game.SimEveryTick (System.Single dt) (at <990b4cf9a7d84305ad7eaef1059b672b>:0)
Game.Update () (at <990b4cf9a7d84305ad7eaef1059b672b>:0)

Build: U47-561558-SD

## Other Mods
I have 134 total mods...not going to list them.

**Comment by romen-h** [comment]
Thanks. Seems like a bug from today's update. I will probably get time to fix it this weekend.

**Comment by mayday6971** [comment]
Also seeing the same issue, and we appreciate your time updating the mod as always! 

MissingMethodException: bool Grid.TestLineOfSight(int,int,int,int,System.Func`2<int, bool>,bool)

RomenH.GermicideLamp.GermicideLamp.UpdateCell (System.Single dt, System.Int32 x, System.Int32 y, System.Collections.Generic.HashSet`1[T] buildingsAlreadySeen) (at <597f3d3d76c94012aee35849ab20d17a>:0)
RomenH.GermicideLamp.GermicideLamp.Sim200ms (System.Single dt) (at <597f3d3d76c94012aee35849ab20d17a>:0)
SimAndRenderScheduler+Sim200msUpdater.Update (ISim200ms updater, System.Single dt) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <0f4b778ef79c497e89f6ee18303840cf>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <0f4b778ef79c497e89f6ee18303840cf>:0)
Game.SimEveryTick (System.Single dt) (at <990b4cf9a7d84305ad7eaef1059b672b>:0)
Game.Update () (at <990b4cf9a7d84305ad7eaef1059b672b>:0)

Build: U47-561558-SD

**Comment by romen-h** [comment]
Uploaded a new build to workshop yesterday that should have fixed this.
