### ISSUE TITLE
[Soggy Carpets] Carpet configuration

### ISSUE THREAD

**Issue by Letarumavza** [romen-h/ONI-Mods#40]
**Is your feature request related to a problem? Please describe.**
The inability to configure fluid flow and buffer tend to limit usages for the carpets.

**Describe the solution you'd like**
A cursor with an input to configure the flow and storage could be a good solution to expand usages of the carpets.

**Describe alternatives you've considered**
A config file could be an alternative to change the carpets properties even if it wouldn't enable more variety in builds at the same time.

**Additional context**
Maybe some code from the liquid valve and liquid reservoir could be repurposed for this feature. Creating a new object for configurable carpets with a higher material cost (like a bit of refined metal) could also be an idea.

**Comment by romen-h** [comment]
I would prefer to make this a setting for the mod and not like a slider on the side-screen for individual buildings.  
My only reason for that is that it's just a carpet and not some complex machine that can be tinkered with.

Maybe another possible solution is to change the buffer capacity based on the element it's made of?

**Comment by romen-h** [comment]
I uploaded a new version to the workshop where you can tweak the settings to your heart's desire.
