### ISSUE TITLE
[Plastic Mesh & Airflow Tiles] Is broken with November Update 

### ISSUE THREAD

**Issue by G-Froh** [romen-h/ONI-Mods#48]
## REQUIRED:  Game crashes when launching, => Black Hole error.

Took me a while but could single out Plastic Mesh & Airflow Tiles as one of the Mods not letting me start my game. 

It´s the only one missing in my current game, in wich i used them a lot.

cheers

**Comment by romen-h** [comment]
Uploaded a new build to the workshop today. Should be fixed!
