### ISSUE TITLE
Stirling Engine lists out of date

### ISSUE THREAD

**Issue by mooklepticon** [romen-h/ONI-Mods#6]
As of 2021-08-12, stirling engine mod lists out of date and can't enable. I do not have the DLC.

**Comment by romen-h** [comment]
It was updated for mergedown on Aug 9.
Your mod version is probably out of date, Steam's fault.
Use Mod Updater to force the latest version to be downloaded.

**Comment by mooklepticon** [comment]
Thanks! No idea why steam won't update it. Mod updater fixed it!
