### ISSUE TITLE
Infinite Gases & Liquids: Game crashes once item is selected

### ISSUE THREAD

**Issue by DarkRavenXC** [romen-h/ONI-Mods#7]
Whenever I select the infinite pump to enter its menu, the game crashes.

Steps To Reproduce
Select the infinite pump.

Logs & Screenshots
![ONI error message Infinite Sinks](https://user-images.githubusercontent.com/90762285/133412707-e10cba70-7b23-4123-ba53-7f7e4e18c0c1.png)

Other Mods
Bigger Capacity 
Big Storage 
Material Selection Properties
Mod Updater 
Mod Manager
Full Miner Yield
Biological Vats 
Build Over Plants
Smart Pumps
Efficient Supply
Wild Planter Box
AI Improvements
Clean Drop
No Planter Box Decor Penalty

If you need any more information, please let me know. This is my first error report on GitHub... I can also provide the save game if that helps.

**Comment by romen-h** [comment]
Thanks for the bug report.

I am aware of the issue and plan to make another build this weekend.
